---
title: pip升级后报错的解决
categories:
  - 未归类
date: 2019-03-04 22:05:04
tags:
---

## 0x01 现象1



升级新版pip后报错

```bash
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```

## 0x02 解决办法

编辑如下文件

> sudo vim /usr/bin/pip

把下面的三行

```python
from pip import main
if __name__ == '__main__':
    sys.exit(main())
```

改为

```bash
from pip import __main__
if __name__ == '__main__':
    sys.exit(__main__._main())
```

## 0x03 现象２

运行pip安装程序报错如下

```bash
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

```

##0x04 解决办法

在终端运行

```
export LC_ALL=C
```

或者将其写入　`.bashrc`

